#!/usr/bin/env python3

# A sample training component that trains a simple scikit-learn decision tree model.
# This implementation works in File mode and makes no assumptions about the input file names.
# Input is specified as CSV with a data point in each row and the labels in the first column.


import os
import json
import pickle
import sys
import traceback
import time
import subprocess

import pandas as pd

from sklearn import tree

# These are the paths to where SageMaker mounts interesting things in your container.

prefix = '/opt/ml/'

input_path = prefix + 'input/data'
output_path = os.path.join(prefix, 'output')
model_path = os.path.join(prefix, 'model')
param_path = os.path.join(prefix, 'input/config/hyperparameters.json')

# This algorithm has a single channel of input data called 'training'. Since we run in
# File mode, the input files are copied to the directory specified here.
channel_name='training'
training_path = os.path.join(input_path, channel_name)


def json_cli(k, v):
    if len(k) > 1:
        param = '--' + k  
    else: 
        param = '-' + k
    v_str = str(v.rstrip(' '))
    if len(v_str):
        param += ' ' + v
    return param

def convert_json_params(dc):
    # params with no argument should be passed with just space string value ' '
    # aws seems to remove keys with empty string!
    params = ' '.join([json_cli(k, v) for k, v in dc.items()])
    return params


# The function to execute the training.
def train():
    print('Starting the training.')
    try:
        # Read in any hyperparameters that the user passed with the training job
        with open(param_path, 'r') as tc:
            pars_dc = json.load(tc)
        print(pars_dc)
        model = os.path.join(model_path, 'model.bin')
        vw_command = 'vw --final_regressor {} {}'.format(
            model, convert_json_params(pars_dc))
        print (vw_command)
        # Note that hyperparameters are always passed in as
        # strings, so we need to do any necessary conversions.

        # TODO should we create the model filename/ data file or expect in params?

        # Take the set of files and read them all into a single pandas dataframe
        input_files = [os.path.join(training_path, file) 
                       for file in os.listdir(training_path) ]
        if len(input_files) == 0:
            raise ValueError(('There are no files in {}.\n' +
                              'This usually indicates that the channel ({}) was incorrectly specified,\n' +
                              'the data specification in S3 was incorrectly specified or the role specified\n' +
                              'does not have permission to access the data.').format(training_path, channel_name))
        start_time = time.time()
        stderr = subprocess.check_output(vw_command,
                                         shell=True,
                                         cwd=training_path,
                                         stderr=subprocess.STDOUT,
                                         timeout=60 * 20).decode('utf-8')
        # timeout in seconds
        with open(os.path.join(model_path, 'results_log.txt'), 'w') as out:
            out.write(stderr)
        print(stderr)
        duration = time.time() - start_time
        print('Training complete in {} seconds.'.format(duration))
    except Exception as e:
        # Write out an error file. This will be returned as the failureReason in the
        # DescribeTrainingJob result.
        trc = traceback.format_exc()
        with open(os.path.join(output_path, 'failure'), 'w') as s:
            s.write('Exception during training: ' + str(e) + '\n' + trc)
        # Printing this causes the exception to be in the training job logs, as well.
        print('Exception during training: ' + str(e) + '\n' + trc, file=sys.stderr)
        # A non-zero exit code causes the training job to be marked as Failed.
        sys.exit(255)

if __name__ == '__main__':
    train()

    # A zero exit code causes the job to be marked a Succeeded.
    sys.exit(0)
